#!/bin/csh -f
#
# architecture specific setup file for CNSsolve
#
# written by: Axel Brunger, Ralf Grosse-Kunstleve and Paul Adams
#
# copyright Yale University
#
# fft library
# use CNS code by default
if ( ! $?CNS_FFTDIR ) then
  setenv CNS_FFTDIR ""
endif
if ( ! $?CNS_FFTLIB ) then
  setenv CNS_FFTLIB ""
endif
#
# set LEXLIB (linux is different from most others)
#
setenv LEXLIB "fl"
#
# -malign-double increases performance, but may cause problems in some cases.
#
setenv CNS_MALIGN_I86 ""
if ( $CNS_ARCH =~ *-i[3456789]86-* ) then
  #setenv CNS_MALIGN_I86 "-malign-double"
endif
#
# machine architecture string for C preprocessor
#
setenv CNS_ARCH_TYPE GFORTRAN_CYGWIN
#
