###############################################################################
#									      #
#       Makefile for CNSsolve input run directory			      #
#       Paul Adams 2-9-98						      #
#       copyright Yale University                                             #
#									      #
###############################################################################

.SUFFIXES:
.SUFFIXES: .sed

SHELL=/bin/sh

FIRSTFILES=

FILES=deposit_mmcif

LINKS=../../xtal_data \
      ../../auxiliary \
      ..

include ../../Makefile.include

deposit_mmcif.sed:
