###############################################################################
#									      #
#       Makefile for CNSsolve input run directory			      #
#       Paul Adams 2-9-98						      #
#	copyright Yale University					      #
#									      #
###############################################################################

.SUFFIXES:
.SUFFIXES: .sed

SHELL=/bin/sh

FIRSTFILES=

FILES=xtal_pdbsubmission

LINKS=../../xtal_data \
      ../../auxiliary \
      ..

include ../../Makefile.include

xtal_pdbsubmission.sed:
