#!/bin/csh -f
#
# architecture specific setup file for CNSsolve
#
# written by: Axel Brunger, Ralf Grosse-Kunstleve and Paul Adams
#
# copyright Yale University
#
# fft library
# use CNS code by default
# see the convex directory for use of the Convex/HP Mlib library
if ( ! $?CNS_FFTDIR ) then
  setenv CNS_FFTDIR ""
endif
if ( ! $?CNS_FFTLIB ) then
  setenv CNS_FFTLIB ""
endif
#
# machine architecture string for C preprocessor
#
setenv CNS_ARCH_TYPE HP
#
