#!/bin/csh -f
#
# architecture specific setup file for CNSsolve
#
# written by: Axel Brunger, Ralf Grosse-Kunstleve and Paul Adams
#
# copyright Yale University
#
# fft library
# use CNS code by default
if ( ! $?CNS_FFTDIR ) then
  setenv CNS_FFTDIR ""
endif
if ( ! $?CNS_FFTLIB ) then
  setenv CNS_FFTLIB ""
endif
#
# optimized libraries
#
setenv CNS_PPC_LIB ""
if ( -e /usr/lib/libmoto.a || \
     -e /usr/lib/libmoto.so ) then
  setenv CNS_PPC_LIB "-lmoto"
endif
#
# machine architecture string for C preprocessor
#
setenv CNS_ARCH_TYPE LINUX
#
